### ISSUE TITLE
Update to readable-stream@3

### ISSUE THREAD

**Issue by wmhilton** [browserify/stream-browserify#17]
It's holding webpack back at `readable-stream@2`.

Also, just genuinely curious... what is this module shimming that isn't provided by `readable-stream`?
I noticed this curiosity in `node-libs-browser` (Webpack's native Node shims):

```js
exports.stream			= require.resolve('stream-browserify');
exports._stream_duplex		= require.resolve('readable-stream/duplex.js');
exports._stream_passthrough	= require.resolve('readable-stream/passthrough.js');
exports._stream_readable	= require.resolve('readable-stream/readable.js');
exports._stream_transform	= require.resolve('readable-stream/transform.js');
exports._stream_writable	= require.resolve('readable-stream/writable.js');
```

Why don't they just use
```js
exports.stream			= require.resolve('readable-stream');
```

**Comment by wmhilton** [comment]
(Genuinely wondering because this module is 3 years old.)

**Comment by goto-bus-stop** [comment]
readable-stream is not quite the same as the 'stream' module in core. readable-stream does not provide the barebones [streams1](http://dominictarr.com/post/145135293917/history-of-streams) API, only streams2+. stream-browserify includes that legacy API.

the _ exports are because you can technically do `require('_stream_readable')` in core. I don't know anything that relies on that, but usually it turns out that something somewhere does :smile_cat:

**Comment by goto-bus-stop** [comment]
i'm working on this for browserify v17 btw, hopefully updating this module this week.

**Comment by wmhilton** [comment]
@goto-bus-stop You're my hero by the way. You've been seriously 🚀 on closing the [Gap List](https://github.com/webpack/node-libs-browser/issues/78)

**Comment by kkamalesh** [comment]
any update on this..im also facing the same issue.

**Comment by guimard** [comment]
Hi,

here is a working patch:
```diff
--- a/index.js
+++ b/index.js
@@ -25,11 +25,11 @@
 var inherits = require('inherits');

 inherits(Stream, EE);
-Stream.Readable = require('readable-stream/readable.js');
-Stream.Writable = require('readable-stream/writable.js');
-Stream.Duplex = require('readable-stream/duplex.js');
-Stream.Transform = require('readable-stream/transform.js');
-Stream.PassThrough = require('readable-stream/passthrough.js');
+Stream.Readable = require('readable-stream/lib/_stream_readable.js');
+Stream.Writable = require('readable-stream/lib/_stream_writable.js');
+Stream.Duplex = require('readable-stream/lib/_stream_duplex.js');
+Stream.Transform = require('readable-stream/lib/_stream_transform.js');
+Stream.PassThrough = require('readable-stream/lib/_stream_passthrough.js');

 // Backwards-compat with node 0.4.x
 Stream.Stream = Stream;
```
